### ISSUE TITLE
Update commonalities glossary with HomeDevicesQoD-subproject relevant terms

### ISSUE THREAD

**Issue by shilpa-padgaonkar** [camaraproject/HomeDevicesQoD#20]
https://github.com/camaraproject/WorkingGroups/pull/120

**Comment by rartych** [comment]
In order to integrate the common glossary in Commonalities it is needed to provide the first version of subproject relevant terms by **15th of March** - it can be placed in this issue within the following table:
| Term      | Description | Usage in API (Parameter/Field) | Alternative developer-friendly terms |
| ------------ | ----------- | ----------- |  ----------- |
| |

**Comment by jpengar** [comment]
| Term      | Description | Usage in API (Parameter/Field) | Alternative developer-friendly terms |
| ------------ | ----------- | ----------- |  ----------- |
| Service Class | A statement of the required QoS characteristics of a traffic aggregate. Conceptually, a service class refers to applications with similar characteristics and performance requirements. Each service class is mapped to a DSCP value according to [RFC4594](https://datatracker.ietf.org/doc/html/rfc4594) guidelines. The DSCP value is used to classify the target home device's traffic so that it can be treated accordingly (i.e. to meet its QoS needs). | service_class | |

**Comment by monamok** [comment]
"service_class" was replaced by "serviceClass" due to the new version of approved guidelines and the decision that was made in [issue#157](https://github.com/camaraproject/WorkingGroups/issues/157) discussion.

**Comment by shilpa-padgaonkar** [comment]
@monamok : The glossary is already merged in commonalities and changes for serviceClass are already in.
Thanks for providing the inputs to the glossary 

https://github.com/camaraproject/WorkingGroups/blob/main/Commonalities/documentation/Glossary.md
