### ISSUE TITLE
Add option to apply QoD to subnets

### ISSUE THREAD

**Issue by RandyLevensalor** [camaraproject/HomeDevicesQoD#46]
**Problem description**
The current API only allows for policies to be applied to a single IP address.  However, more homes are beginning to segment their networks and could have different WoD settings based on the subnet.

For instance, traffic on a home office subnet would be treated differently than a guest or IoT subnet.

**Possible evolution**
There are several approaches to solve this.

One is to replace the `ipAddress` property with `networkCIDR`

For IPv4, the would be a network address followed by a network mask.  `192.168.1.0/24` or to specify a single IP `192.168.1.19/128`

To preserve backwards compatibility, the API calls could be changed to:

```yaml
oneOf:
  - ipAddress
  - networkCIDR
```

**Alternative solution**

**Additional context**

**Comment by jpengar** [comment]
@RandyLevensalor Thank you for your feedback. It is indeed interesting. But according to the OpenGateway procedure, new features should be handled this way:

GSMA OGW Product WS --> OGW Backlog Prioritization (Voting) --> CAMARA Backlog

If you want to add new features that affect the functionality of the service (not just technical changes to an existing one), it's preferable to follow this path, since GSMA is the one that manages priorities at the product level. Let us know if you need assistance in reaching this track. (CC @jgarciahospital)

In any case, from my perspective, the extension you suggest is probably more appropriate for an internal Operator application, where the user has a "control panel" or similar to manage their home network resources, devices and configurations (including subnets). But in the CAMARA context, where Operator exposes APIs to third party developers, the subnet information may not be known/accessible to the developer (exposed information is limited). I don't quite see the use case for an app (say Zoom app) running on my laptop (connected to my home network) requesting to apply QoD for a "work" subnet instead of the device IP corresponding to my laptop...

**Comment by jpengar** [comment]
Closed as there were no further objections and the Open Gateway procedure for requesting new features was mentioned.
